TRAIN:
  ENABLE: True
  DATASET: Interaction
  BATCH_SIZE: 32
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
DATA:
  NUM_FRAMES: 4
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
  MULTI_LABEL: True
  PATH_TO_DATA_DIR: "/media/kiyoaki/Ventoy/projects/SlowFast-Interaction/data/interaction/clip/2022/w1"
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 18
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  # NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  NUM_BLOCK_TEMP_KERNEL: [ [ 2, 2 ], [ 2, 2 ], [ 2, 2 ], [ 2, 2 ] ]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 1e-3
  LR_POLICY: cosine
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 8.0
  WARMUP_START_LR: 1e-4
  OPTIMIZING_METHOD: adam
MODEL:
  NUM_CLASSES: 5 # Actual num should be lower than this
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: bce_logit
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: False
  DATASET: Interaction
  BATCH_SIZE: 32
DATA_LOADER:
  NUM_WORKERS: 6
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: ../outputs/w1/slowfast


TENSORBOARD:
  ENABLE: True
  MODEL_VIS:
    ENABLE: False
    MODEL_WEIGHTS: False # Set to True to visualize model weights.
    ACTIVATIONS: False # Set to True to visualize feature maps.
    INPUT_VIDEO: False # Set to True to visualize the input video(s) for the corresponding feature maps.
    LAYER_LIST: # List of layer names to visualize weights and activations for.
      - 's5'
      - 's4_fuse'
    GRAD_CAM:
      ENABLE: False
      LAYER_LIST: # List of CNN layers to use for Grad-CAM visualization method. # The number of layer must be equal to the number of pathway(s).
        - 's5'
        - 's4_fuse'
