TRAIN:
  # ENABLE: False # default True
  DATASET: Interaction_ua_2022
  BATCH_SIZE: 48
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
X3D:
  WIDTH_FACTOR: 2.0
  DEPTH_FACTOR: 2.2
  BOTTLENECK_FACTOR: 2.25
  DIM_C5: 2048
  DIM_C1: 12
TEST:
  ENABLE: True
  DATASET: Interaction_ua_2022
  BATCH_SIZE: 96
  # CHECKPOINT_FILE_PATH: 'x3d_s.pyth' # 73.50% top1 30-view accuracy to download from the model zoo (optional).
  # NUM_SPATIAL_CROPS: 1
  NUM_SPATIAL_CROPS: 3
DATA:
  NUM_FRAMES: 4
  SAMPLING_RATE: 6
  TRAIN_JITTER_SCALES: [182, 228]
  TRAIN_CROP_SIZE: 160
  # TEST_CROP_SIZE: 160 # use if TEST.NUM_SPATIAL_CROPS: 1
  TEST_CROP_SIZE: 182 # use if TEST.NUM_SPATIAL_CROPS: 3
  INPUT_CHANNEL_NUM: [3]
  DECODING_BACKEND: torchvision
  PATH_TO_DATA_DIR: "/media/kiyoaki/Ventoy/projects/SlowFast-Interaction/data/interaction/clip/2022/csv/wall"
RESNET:
  ZERO_INIT_FINAL_BN: True
  TRANS_FUNC: x3d_transform
  STRIDE_1X1: False
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 1e-3 # 16 machine
  BASE_LR_SCALE_NUM_SHARDS: True
  LR_POLICY: cosine
  MAX_EPOCH: 20
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 1.0
  WARMUP_START_LR: 1e-4
  OPTIMIZING_METHOD: adam
MODEL:
  NUM_CLASSES: 2
  ARCH: x3d
  MODEL_NAME: X3D
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 1
RNG_SEED: 0
OUTPUT_DIR: "../outputs/interaction/2022/w1/x3d/ua/1_w1234_sampling"
TENSORBOARD:
  ENABLE: True
  CLASS_NAMES_PATH: "../src/config/names/class_id_ua.json"
  MODEL_VIS:
    ENABLE: True
    MODEL_WEIGHTS: False
    ACTIVATIONS: False
    INPUT_VIDEO: False
    LAYER_LIST: ['dim_res5'] # List of layer names to visualize weights and activations for.
    GRAD_CAM:
      ENABLE: True
      USE_TRUE_LABEL: False
      # OUTPUT_DIR: "../outputs/interaction/2022/w1/x3d/ua/1_w1234_sampling/grad_cam"
      LAYER_LIST: ['dim_res5'] # The number of layer must be equal to the number of pathway(s).
